### use blance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "9709526468",
  "amount": 1000
}
### use blance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "9709526468",
  "amount": 100
}

### cancel blance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "988e59110c4d483ba809161fed36cf3d",
  "accountNumber": "9709526468",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/a626e3cee26447638ea3cf49cc09812d
