### use blance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}
### use blance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### cancel blance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "ab6747e0033f4caaae661c922401cb94",
  "accountNumber": "1000000002",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/6158fb6020f148269d9960824d2c27c7
